theme: jekyll-theme-architect
title: Welcome to Joseph Figueroa's homepage!
description: Welcome to my portfolio, Here you can find my personal and professional projects that I am currently working on.
